#!/bin/bash
# This file is a draft for local testing, not fully working yet.

# sudo apt install evemu-tools evtest
# sudo ./tests/test_limux.sh

echo "1. Creating a virtual physical device (Fake Keyboard)..."
# evemu-device /usr/share/evemu/devices/keyboard-usb-generic.json &
evemu-device ./tests/keyboard.desc &
EVEMU_PID=$!
sleep 1 # Waits for the kernel to register the device

# Discover the path of the newly created fake device.
FAKE_DEV=$(grep -E 'Name="evemu-device|Generic USB Keyboard"' /proc/bus/input/devices -A 4 | grep Handlers | tail -n 1 | awk '{print $2}' | sed 's/^/\/dev\/input\//')
echo "Dispositivo falso criado em: $FAKE_DEV"

echo "2. Iniciando o LIMux..."
# # Replace the path below with the compiled executable of your program
# ./../target/debug/limulx-linux-input-multiplexer --device $FAKE_DEV --initial-delay 200 --rapid-fire-delay 50 &
./target/debug/limulx-linux-input-multiplexer --device $FAKE_DEV --initial-delay 200 --rapid-fire-delay 50 &
LIMUX_PID=$!
sleep 1

echo "3. Identifying the virtual keyboard created by LIMux..."
VIRTUAL_DEV=$(grep 'Name="LIMulx' /proc/bus/input/devices -A 4 | grep Handlers | grep -o 'event[0-9]*')
VIRTUAL_DEV="/dev/input/$VIRTUAL_DEV"
echo "LIMux keyboard found in: $VIRTUAL_DEV"

echo "4. Starting capture (evtest)..."
evtest $VIRTUAL_DEV > limux_output.log &
EVTEST_PID=$!

echo "5. Simulating a key press (Holding 'W' for 1 second)..."
# Injeta KeyDown (1) da tecla W (código 17)
evemu-event $FAKE_DEV --type EV_KEY --code 17 --value 1 --sync
# Aguarda 1 segundo (tempo suficiente para o rapid-fire disparar várias vezes)
sleep 1
# Injeta KeyUp (0) da tecla W (código 17)
evemu-event $FAKE_DEV --type EV_KEY --code 17 --value 0 --sync

sleep 0.5

echo "6. Cleaning up processes..."
kill $EVTEST_PID $LIMUX_PID $EVEMU_PID

echo "Test completed. Result saved to 'linux output.log'."
echo "Summary of key events generated by LIMux:"
grep "Event: time.*type 1 (EV_KEY)" limux_output.log